version: '3.7'
services:
  tree-db:
    image: blacklabelops/hsqldb
    container_name: tree-db
    ports:
      - "9001:9001"
    volumes:
      - ./dbdata:/opt/database
    env_file:
      - docker-compose.env
    labels:
      com.blacklabelops.description: "HSQL Development System"
      com.blacklabelops.service: "hsqldb-server"