version: '3.7'
services:
  tree-db:
    image: postgres
    container_name: tree-db
    ports:
      - "5432:5432"
    volumes:
      - ./db-files:/docker-entrypoint-initdb.d

    environment:
      POSTGRES_PASSWORD: mysecretpassword
